# This file is distributed under the same license as the Django package.
#
# Translators:
# Jannis Leidel <jannis@leidel.info>, 2011
# arupakan125 <koh@arupaka.net>, 2020
# Masashi SHIBATA <contact@c-bata.link>, 2017
# Nikita K <hiyori.amatsuki@gmail.com>, 2019
# Shinya Okano <tokibito@gmail.com>, 2013-2016
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-07-07 10:01+0100\n"
"PO-Revision-Date: 2020-01-20 06:25+0000\n"
"Last-Translator: arupakan125 <koh@arupaka.net>\n"
"Language-Team: Japanese (http://www.transifex.com/django/django/language/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:46
msgid "Personal info"
msgstr "個人情報"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:47
msgid "Permissions"
msgstr "パーミッション"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:50
msgid "Important dates"
msgstr "重要な日程"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:134
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "主キーが %(key)r である %(name)s オブジェクトは存在しません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:144
msgid "Password changed successfully."
msgstr "パスワードを変更しました"

#: env/lib/python3.7/site-packages/django/contrib/auth/admin.py:164
#, python-format
msgid "Change password: %s"
msgstr "パスワードの変更: %s"

#: env/lib/python3.7/site-packages/django/contrib/auth/apps.py:15
msgid "Authentication and Authorization"
msgstr "認証と認可"

#: env/lib/python3.7/site-packages/django/contrib/auth/base_user.py:48
msgid "password"
msgstr "パスワード"

#: env/lib/python3.7/site-packages/django/contrib/auth/base_user.py:49
msgid "last login"
msgstr "最終ログイン"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:40
msgid "No password set."
msgstr "パスワードは設定されませんでした。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:45
msgid "Invalid password format or unknown hashing algorithm."
msgstr "無効なパスワードか不明なハッシュアルゴリズムです。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:87
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:334
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:407
msgid "The two password fields didn’t match."
msgstr "確認用パスワードが一致しません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:90
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:143
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:179
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:411
msgid "Password"
msgstr "パスワード"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:96
msgid "Password confirmation"
msgstr "パスワード(確認用)"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:99
#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:420
msgid "Enter the same password as before, for verification."
msgstr "確認のため、再度パスワードを入力してください。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:145
msgid ""
"Raw passwords are not stored, so there is no way to see this user’s "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""
"生のパスワードは格納されていないため、このユーザのパスワードを確認する方法は"
"ありません。しかし<a href=\"{}\">このフォーム</a>を使用してパスワードを変更で"
"きます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:186
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"正しい%(username)sとパスワードを入力してください。どちらのフィールドも大文字"
"と小文字は区別されます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:189
msgid "This account is inactive."
msgstr "アカウントが無効です。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:252
msgid "Email"
msgstr "メールアドレス"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:337
msgid "New password"
msgstr "新しいパスワード"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:343
msgid "New password confirmation"
msgstr "新しいパスワード(確認用)"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:379
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "元のパスワードが間違っています。もう一度入力してください。"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:382
msgid "Old password"
msgstr "元のパスワード"

#: env/lib/python3.7/site-packages/django/contrib/auth/forms.py:417
msgid "Password (again)"
msgstr "パスワード(確認用)"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:259
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:333
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:429
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:489
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:520
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:556
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:592
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:630
msgid "algorithm"
msgstr "アルゴリズム"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:260
msgid "iterations"
msgstr "イテレーション"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:261
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:339
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:431
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:490
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:521
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:631
msgid "salt"
msgstr "ソルト"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:262
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:340
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:491
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:522
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:557
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:593
#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:632
msgid "hash"
msgstr "ハッシュ"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:334
msgid "variety"
msgstr "多様性"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:335
msgid "version"
msgstr "バージョン"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:336
msgid "memory cost"
msgstr "メモリーコスト"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:337
msgid "time cost"
msgstr "時間コスト"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:338
msgid "parallelism"
msgstr "並行性"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:430
msgid "work factor"
msgstr "ワークファクター"

#: env/lib/python3.7/site-packages/django/contrib/auth/hashers.py:432
msgid "checksum"
msgstr "チェックサム"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:56
#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:108
msgid "name"
msgstr "名前"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:60
msgid "content type"
msgstr "コンテンツタイプ"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:62
msgid "codename"
msgstr "コード名"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:67
msgid "permission"
msgstr "パーミッション"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:68
#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:111
msgid "permissions"
msgstr "パーミッション"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:118
msgid "group"
msgstr "グループ"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:119
#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:242
msgid "groups"
msgstr "グループ"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:233
msgid "superuser status"
msgstr "スーパーユーザー権限"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:236
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "全ての権限を持っているとみなされます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:245
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""
"このユーザーが所属するグループ。ユーザーはそれぞれのグループに付与されたすべ"
"ての権限を持ちます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:253
msgid "user permissions"
msgstr "ユーザーパーミッション"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:255
msgid "Specific permissions for this user."
msgstr "このユーザーの持つ権限です。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:326
msgid "username"
msgstr "ユーザー名"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:329
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にし"
"てください。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:332
msgid "A user with that username already exists."
msgstr "同じユーザー名が既に登録済みです。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:335
msgid "first name"
msgstr "名"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:336
msgid "last name"
msgstr "姓"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:337
msgid "email address"
msgstr "メールアドレス"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:339
msgid "staff status"
msgstr "スタッフ権限"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:341
msgid "Designates whether the user can log into this admin site."
msgstr "ユーザーが管理サイトにログイン可能かどうかを示します。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:344
msgid "active"
msgstr "有効"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:347
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"ユーザーがアクティブかどうかを示します。アカウントを削除する代わりに選択を解"
"除してください。"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:351
msgid "date joined"
msgstr "登録日"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:360
msgid "user"
msgstr "ユーザー"

#: env/lib/python3.7/site-packages/django/contrib/auth/models.py:361
msgid "users"
msgstr "ユーザー"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:102
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] "このパスワードは短すぎます。最低 %(min_length)d 文字以上必要です。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:112
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] "パスワードは最低 %(min_length)d 文字以上必要です。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:151
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr "このパスワードは %(verbose_name)s と似すぎています。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:157
msgid "Your password can’t be too similar to your other personal information."
msgstr "あなたの他の個人情報と似ているパスワードにはできません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:183
msgid "This password is too common."
msgstr "このパスワードは一般的すぎます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:188
msgid "Your password can’t be a commonly used password."
msgstr "よく使われるパスワードにはできません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:198
msgid "This password is entirely numeric."
msgstr "このパスワードは数字しか使われていません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/password_validation.py:203
msgid "Your password can’t be entirely numeric."
msgstr "数字だけのパスワードにはできません。"

#: env/lib/python3.7/site-packages/django/contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s のパスワードリセット"

#: env/lib/python3.7/site-packages/django/contrib/auth/validators.py:12
msgid ""
"Enter a valid username. This value may contain only English letters, "
"numbers, and @/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:160
msgid "Logged out"
msgstr "ログアウト"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:217
msgid "Password reset"
msgstr "パスワードをリセット"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:244
msgid "Password reset sent"
msgstr "パスワードリセットを送信しました"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:254
msgid "Enter new password"
msgstr "新しいパスワードを入力してください"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:314
msgid "Password reset unsuccessful"
msgstr "パスワードのリセットに失敗しました"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:322
msgid "Password reset complete"
msgstr "パスワードがリセットされました"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:334
msgid "Password change"
msgstr "パスワードの変更"

#: env/lib/python3.7/site-packages/django/contrib/auth/views.py:357
msgid "Password change successful"
msgstr "パスワードを変更しました"
